run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - revive
    - govet
    - gosec
    - errcheck
  disable:
    - wsl

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
