run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - go/pkg/mod

  exclude-rules:
    - path: go/pkg/mod/.*
      linters:
        - all

linters:
  enable:
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
  disable:
    - wsl
    - dupl
