version: "3"

vars:
  DOCKER_COMPOSE_FILE: ./deployments/docker-compose.yml

tasks:
  test:
    cmds:
      - go test ./...

  build:
    cmds:
      - docker compose --env-file .env -f {{.DOCKER_COMPOSE_FILE}} build

  up:
    cmds:
      - docker compose --env-file .env -f {{.DOCKER_COMPOSE_FILE}} up

  down:
    cmds:
      - docker compose --env-file .env -f {{.DOCKER_COMPOSE_FILE}} down

  generate:
    cmds:
      - cd api/proto && buf generate
